### ISSUE TITLE
Adding DSA Algorithms and Leetcode question Solutions

### ISSUE THREAD

**Issue by Kritika30032002** [risingstar-bit/Compose-Community#109]
Adding 
1. Binary Search Algorithm
2. Sqrt(x)
3. Find Peak Element
4. Find All Duplicates in an Array
5. Number of 1 Bits

Assign this issue to me !!

**Comment by risingstar-bit** [comment]
> Adding
> 
> 1. Binary Search Algorithm
> 2. Sqrt(x)
> 3. Find Peak Element
> 4. Find All Duplicates in an Array
> 5. Number of 1 Bits
> 
> Assign this issue to me !!

Make sure you put these in their respective folders. Also it shouldn't be already present.

**Comment by Kritika30032002** [comment]
Okay Sure!!

**Comment by Kritika30032002** [comment]
Binary Search was already there Therefore added Bubble sort.
