### ISSUE TITLE
Kadane’s Algorithm : Maximum Subarray Sum in an Array in c++

### ISSUE THREAD

**Issue by SonaVarshney** [risingstar-bit/Compose-Community#134]
Want to add kadane's algorithm in c++, it is a very efficient algorithm to find max sum subarray of an array, pls assign me this issue

**Comment by risingstar-bit** [comment]
> Want to add kadane's algorithm in c++, it is a very efficient algorithm to find max sum subarray of an array, pls assign me this issue

DO it

**Comment by SonaVarshney** [comment]
@risingstar-bit , pls checkout the pr made https://github.com/risingstar-bit/Compose-Community/pull/137#issue-1407154994 ,
thanks
