### ISSUE TITLE
20_Valid Parentheses Leetcode question

### ISSUE THREAD

**Issue by SonaVarshney** [risingstar-bit/Compose-Community#135]
want to add c++ solution of this problem.

Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.

An input string is valid if:

Open brackets must be closed by the same type of brackets.
Open brackets must be closed in the correct order.
Every close bracket has a corresponding open bracket of the same type.

Please assign me this problem

**Comment by risingstar-bit** [comment]
> want to add c++ solution of this problem.
> 
> Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.
> 
> An input string is valid if:
> 
> Open brackets must be closed by the same type of brackets. Open brackets must be closed in the correct order. Every close bracket has a corresponding open bracket of the same type.
> 
> Please assign me this problem

okay do it. Before committing follow the folders sequence and add your code  in proper folder.

**Comment by SonaVarshney** [comment]
@risingstar-bit please check https://github.com/risingstar-bit/Compose-Community/pull/139#issue-1407566234

**Comment by risingstar-bit** [comment]
> 

good.
