### ISSUE TITLE
Adding a Tin-Dog Website

### ISSUE THREAD

**Issue by Kritika30032002** [risingstar-bit/Compose-Community#146]
Adding a basic frontend project.

Assign this issue to me!!

**Comment by Kritika30032002** [comment]
Its only a frontend website



![Tin dog website](https://user-images.githubusercontent.com/83400697/195748155-5f91d942-0203-4d03-8921-c811f74206f0.png)


> > Adding a basic frontend project.
> > Assign this issue to me!!
> 
> First Send me the demo how it works.

Its only a frontend website



![Tin dog website](https://user-images.githubusercontent.com/83400697/195748155-5f91d942-0203-4d03-8921-c811f74206f0.png)

**Comment by Kritika30032002** [comment]
@risingstar-bit

**Comment by Kritika30032002** [comment]
@risingstar-bit

**Comment by risingstar-bit** [comment]
> @risingstar-bit
I am merging this time but try to make real life related project. Add backend too.

**Comment by Kritika30032002** [comment]
> > @risingstar-bit
> > I am merging this time but try to make real life related project. Add backend too.

Okay But frontend projects also exits!

**Comment by Kritika30032002** [comment]
> > @risingstar-bit
> > I am merging this time but try to make real life related project. Add backend too.

Assign this to me
