### ISSUE TITLE
Adding A Dice Challenge Website

### ISSUE THREAD

**Issue by Kritika30032002** [risingstar-bit/Compose-Community#147]
Adding A dice Challenge Website 

Assign this issue to me!!

**Comment by Kritika30032002** [comment]
@risingstar-bit

**Comment by Kritika30032002** [comment]
@risingstar-bit

**Comment by risingstar-bit** [comment]
send me the demo @Kritika30032002

**Comment by Kritika30032002** [comment]
![Screenshot (19456)](https://user-images.githubusercontent.com/83400697/195991591-978ea0fd-f3dc-4004-bfad-2dc9b918d0ba.png)
![Screenshot (19457)](https://user-images.githubusercontent.com/83400697/195991595-f70fdb5b-0879-4666-9db8-4a229e7fd0b1.png)
![Screenshot (19455)](https://user-images.githubusercontent.com/83400697/195991597-e986b3e8-5d6c-403a-8ced-6e248a0abda9.png)


@risingstar-bit

**Comment by Kritika30032002** [comment]
@risingstar-bit

**Comment by Kritika30032002** [comment]
@risingstar-bit

**Comment by risingstar-bit** [comment]
> 

@Kritika30032002 Please try to make it more attractive. keep all the lining space similar.
