### ISSUE TITLE
Updating README.md of Javascript Projects Folder 

### ISSUE THREAD

**Issue by Swap-nil-2003** [risingstar-bit/Compose-Community#158]
The Javascript folder under Projects needs an update to the README.md as new projects have been added.

**Comment by risingstar-bit** [comment]
> The Javascript folder under Projects needs an update to the README.md as new projects have been added.

Please add the README.md file for each project of Javascript in their respective folder. Go through each project understand it then drop README.md file to it. Procced if you can.

**Comment by Swap-nil-2003** [comment]
@risingstar-bit yes sure, please assign me the issue.
