### ISSUE TITLE
Add cheatsheets of different technical skills on cheatsheets folder. Make sure to give proper name to your file.

### ISSUE THREAD

**Issue by risingstar-bit** [risingstar-bit/Compose-Community#16]

**Comment by mehraankush** [comment]
how many skills i need to add .. ?

**Comment by risingstar-bit** [comment]
> how many skills i need to add .. ?

atleast 1

**Comment by risingstar-bit** [comment]
> > how many skills i need to add .. ?
> 
> atleast 1

make sure that your tech. skill is different from already existing on cheatsheets folder

**Comment by mehraankush** [comment]
ok then i will do that assign it to me .
