### ISSUE TITLE
41. First missing positive Leetcode problem in C++

### ISSUE THREAD

**Issue by SonaVarshney** [risingstar-bit/Compose-Community#171]
Want to add the C++ solution of this problem. pls assign me.

**Comment by risingstar-bit** [comment]
> Want to add the C++ solution of this problem. pls assign me.

Yes Proceed

**Comment by SonaVarshney** [comment]
https://github.com/risingstar-bit/Compose-Community/pull/178#issue-1416425692 pls have a look @risingstar-bit

**Comment by SonaVarshney** [comment]
@risingstar-bit
