### ISSUE TITLE
Add .gitignore file to this repository

### ISSUE THREAD

**Issue by risingstar-bit** [risingstar-bit/Compose-Community#18]

**Comment by sid172014** [comment]
Hey , can you please assign this to me ? I would love to work on this

**Comment by risingstar-bit** [comment]
@sid172014 assigned.

**Comment by sid172014** [comment]
Hey ive added gitignore and made a pull request can you please have a look?...

**Comment by risingstar-bit** [comment]
give a star to this repo. Thank You
