### ISSUE TITLE
On Egg Timer App, when the times get over and the sound hits, make pausesound button visible and when go button is pressed make pausesound button invisible .

### ISSUE THREAD

**Issue by risingstar-bit** [risingstar-bit/Compose-Community#20]

**Comment by Sakshi-75** [comment]
Hi @risingstar-bit ,
I would like to work on this. Can you assign it to me please?

**Comment by risingstar-bit** [comment]
@Sakshi-75 assigned.

**Comment by Sakshi-75** [comment]
Hi @risingstar-bit ,
I'm facing some setup related issues for this and because of that I'm unable to work on it.
Can you unassign me from this so someone else could pick it up?
Sorry about the inconvenience caused.

**Comment by risingstar-bit** [comment]
> Hi @risingstar-bit , I'm facing some setup related issues for this and because of that I'm unable to work on it. Can you unassign me from this so someone else could pick it up? Sorry about the inconvenience caused.

okay no problem.
