### ISSUE TITLE
Aggressive_Cows_Problem

### ISSUE THREAD

**Issue by GargNikitaa** [risingstar-bit/Compose-Community#203]

**Comment by GargNikitaa** [comment]
Pls assign this issue to me

**Comment by GargNikitaa** [comment]
https://github.com/risingstar-bit/Compose-Community/pull/204#issue-1424054729 @risingstar-bit Kindly have a look

**Comment by risingstar-bit** [comment]
> [#204 (comment)](https://github.com/risingstar-bit/Compose-Community/pull/204#issue-1424054729) @risingstar-bit Kindly have a look

Okay Proceed

**Comment by GargNikitaa** [comment]
https://github.com/risingstar-bit/Compose-Community/pull/204#issue-1424054729 @risingstar-bit I have made the PR pls check

**Comment by risingstar-bit** [comment]
> [#204 (comment)](https://github.com/risingstar-bit/Compose-Community/pull/204#issue-1424054729) @risingstar-bit I have made the PR pls check

Already merged your PR
