### ISSUE TITLE
Upload Road Map on Android Development/DSA/Communication Skills.

### ISSUE THREAD

**Issue by risingstar-bit** [risingstar-bit/Compose-Community#23]

**Comment by ArcheR1901** [comment]
Please assign me this piece of work. I would like to contribute.

**Comment by ArcheR1901** [comment]
Hi, I have been un assigned from this issue. Can you please assign me back if it is possible and if it makes any sense after the PR has been merged

**Comment by risingstar-bit** [comment]
> Hi, I have been un assigned from this issue. Can you please assign me back if it is possible and if it makes any sense after the PR has been merged

Already added. If you wish to add any other tech Roadmap you can proceed

**Comment by ArcheR1901** [comment]
Ok. I think there is an issue in Github, because on the original issue I am
assigned, but in the pull requests I am not. I don't know what this glitch
is.

**Comment by ArcheR1901** [comment]
Hi, I am sending a screenshot. Here, you can see I was assigned and then
unassigned. As well as, on the right side, there is no one assigned. May be
a glitch in Github or something else.
