### ISSUE TITLE
Upload Git&GitHub cheatsheet on cheatsheet folder, if not present create a folder "Cheatsheets" in main then add your file on it. 

### ISSUE THREAD

**Issue by risingstar-bit** [risingstar-bit/Compose-Community#26]

**Comment by yash-sharma13** [comment]
Hey I would like to work on this one. please assign me.. 
also please add hacktoberfest-accepted tag

**Comment by ArcheR1901** [comment]
Hey @risingstar-bit I would like to work on this issue. Please assign me this piece of work.

**Comment by risingstar-bit** [comment]
@yash-sharma13 let @ArcheR1901 create Cheatsheets folder and a file in it. After it gets merged i will mention you to add another cheatsheet.

**Comment by yash-sharma13** [comment]
@risingstar-bit  sorry I saw it a bit late, I was working on the cheatsheet I'll pr it.. Please check it out and merge it if you like.
