### ISSUE TITLE
Add a cheatsheet of keyboard shortcuts in CheatSheets folder

### ISSUE THREAD

**Issue by risingstar-bit** [risingstar-bit/Compose-Community#37]

**Comment by S-Parker7000** [comment]
I am on it

**Comment by risingstar-bit** [comment]
> I am on it

yeah do it

**Comment by ArcheR1901** [comment]
@risingstar-bit Can you please assign me this task.

**Comment by varsha-kss** [comment]
can i be assigned this task?

**Comment by risingstar-bit** [comment]
@varsha-kss @ArcheR1901 I already merged it. You can add another technical skills ex- Android dev, web dec, dsa, java, linux etc. as it is much in demanding

**Comment by Ankitrai2204** [comment]
Hello I want to contribute on this project. Can you please assign it to me and tell about our requirements.
