### ISSUE TITLE
Add java string notes in Notes folder. File name should be Java_String.

### ISSUE THREAD

**Issue by risingstar-bit** [risingstar-bit/Compose-Community#39]

**Comment by DivvSaxena** [comment]
i am not able to find location of that file

**Comment by risingstar-bit** [comment]
@DivvSaxena move to Notes folder create a file "Java_String"

**Comment by DivvSaxena** [comment]
assign it to me

**Comment by DivvSaxena** [comment]
We have to just  make a file of Java_String in the notes folder

**Comment by risingstar-bit** [comment]
> We have to just make a file of Java_String in the notes folder

yes

**Comment by DivvSaxena** [comment]
made it #49

**Comment by MinalGhate** [comment]
Hey, I would like to work on this issue

**Comment by risingstar-bit** [comment]
> Hey, I would like to work on this issue
yes ho ahead
