### ISSUE TITLE
Add different DSA algorithm

### ISSUE THREAD

**Issue by sudipg4112001** [risingstar-bit/Compose-Community#61]
Illustration of different DSA algorithms are wanted. 
Please contribute to `DSA/Language Name/Folder(Algorithm)/Script`

If folders for your suitable language is not included please add one, and then contribute.

**Comment by Decent-Sanage** [comment]
I'll do it

**Comment by sudipg4112001** [comment]
> I'll do it
Please proceed. Follow contributor's guideline.

**Comment by AryamanAdivyaSingh47** [comment]
I would also like to contribute in this repository as my first issue and participation in Hacktoberfest 2022

**Comment by Suryanshj45** [comment]
I have added few files and sent the pull request can you please verify

**Comment by purbendu** [comment]
I would also like to contribute in this repository.

**Comment by risingstar-bit** [comment]
> I would also like to contribute in this repository.

okay contribute. But make sure your algorithm is different from already added algorithms.

**Comment by deepesh85b** [comment]
@sudipg4112001 
Please assign this to me
