### ISSUE TITLE
Add different projects

### ISSUE THREAD

**Issue by sudipg4112001** [risingstar-bit/Compose-Community#62]
This repo is open for all tech stacks please add any kind of projects you are comfortable with.

- **Accepting projects across all domains**

- Please contribute in the `project` folder with proper file name.

**Comment by atom540** [comment]
can you assign this to me?

**Comment by MayankUghade** [comment]
@sudipg4112001 I would like to work for it.

**Comment by SmartAree** [comment]
Can I add my Flutter Project??

**Comment by risingstar-bit** [comment]
> can you assign this to me?

go ahead. Make sure your project is different from contributed ones.

**Comment by risingstar-bit** [comment]
> Can I add my Flutter Project??

Sure. It should be different contributed projects.

**Comment by risingstar-bit** [comment]
> @sudipg4112001 I would like to work for it.

yes please

**Comment by YuvrajRakheja** [comment]
I would love to contribute.Please assign @risingstar-bit

**Comment by risingstar-bit** [comment]
> I would love to contribute.Please assign @risingstar-bit

yes do it. Make sure that it doesn't match with the contributed projects

**Comment by Kritika30032002** [comment]
may i contribute to this?

**Comment by risingstar-bit** [comment]
> may i contribute to this? @risingstar-bit

Yes proceed. But it should not be copied from internet

**Comment by Kritika30032002** [comment]
> > may i contribute to this? @risingstar-bit
> 
> Yes proceed. But it should not be copied from internet

yeah of course!!

**Comment by Sravani565** [comment]
May I contribute to this??

**Comment by 34sravani-g** [comment]
Shall I contribute to this??

**Comment by tanyaa-arora** [comment]
Can I contribute to this task?

**Comment by risingstar-bit** [comment]
> Shall I contribute to this??

yes proceed

**Comment by risingstar-bit** [comment]
> Can I contribute to this task?

yes sure
