### ISSUE TITLE
Want to add some DSA problem solution in c++ language

### ISSUE THREAD

**Issue by Suryanshj45** [risingstar-bit/Compose-Community#66]

**Comment by sudipg4112001** [comment]
Make make folder for c++ inside DSA. Then put your code with a proper resume file

**Comment by Suryanshj45** [comment]
ok

**Comment by Suryanshj45** [comment]
I should first fork this repository and then add the folder, and then I should send you the pull request right?

**Comment by sudipg4112001** [comment]
> I should first fork this repository and then add the folder, and then I should send you the pull request right?

Do everything in your own local repository then make a pr

**Comment by Mr-Sahil-Alam** [comment]
Please assign this to me

**Comment by Kabir1302** [comment]
Please assign this to me.

**Comment by risingstar-bit** [comment]
@Mr-Sahil-Alam @Kabir1302 make sure your problems shouldn't be already present in Cpp folder. you have to add your source code file in cpp folder

**Comment by Sravani565** [comment]
Please assign this to me

**Comment by 34sravani-g** [comment]
Can you please assign this to me

**Comment by risingstar-bit** [comment]
@Sravani565 @Sravani565  make sure your problems shouldn't be already present in Cpp folder. you have to add your source code file in cpp folder

**Comment by dollykumari9798** [comment]
Hey @risingstar-bit, can I work on this issue?
