### ISSUE TITLE
Add Bubble Sort in Algorithm folder

### ISSUE THREAD

**Issue by risingstar-bit** [risingstar-bit/Compose-Community#75]
There is a folder "Bubble sort" in DSA/JAVA/Algorithm you need to add java source file (your code) and readme file describing algorithm in details.

**Comment by probro27** [comment]
Would love to work on this @risingstar-bit . Please assign this to me :)

**Comment by risingstar-bit** [comment]
> Would love to work on this @risingstar-bit . Please assign this to me :)

Assigned👍

**Comment by probro27** [comment]
Thanks :)

**Comment by YuvrajRakheja** [comment]
Please assign.I am done with it.@risingstar-bit.Will make pr immediately.

**Comment by risingstar-bit** [comment]
> Please assign.I am done with it.@risingstar-bit .Will make pr immediately.

You didn't ask me to assign this.

**Comment by Kritika30032002** [comment]
Bubble sort is already added
