### ISSUE TITLE
Add selection sort algorithm 

### ISSUE THREAD

**Issue by risingstar-bit** [risingstar-bit/Compose-Community#76]

**Comment by risingstar-bit** [comment]
Go to DSA/JAVA/Algorithm/Selection sort add java source code and Readme file describing its algorithm.

**Comment by RibhavKhanna** [comment]
please assign me this issue @risingstar-bit

**Comment by risingstar-bit** [comment]
> please assign me this issue @risingstar-bit

yes sure. Add only README.md file because source code is already present.
