### ISSUE TITLE
Data Structure C++ | DFS and BFS for Binary Tree

### ISSUE THREAD

**Issue by hamzaziizzz** [risingstar-bit/Compose-Community#85]
Hii!! @risingstar-bit 
I want to contribute C++ code for Breadth-First and Depth-First Traversal for Binary. If you find it useful, please assign it to me.

**Comment by risingstar-bit** [comment]
> Hii!! @risingstar-bit I want to contribute C++ code for Breadth-First and Depth-First Traversal for Binary. If you find it useful, please assign it to me.

first see in the folder if it is already present then add other algorithm else proceed

**Comment by hamzaziizzz** [comment]
I have checked the folder, it is not already present there, so I am proceeding with it.
