### ISSUE TITLE
Add README files for each C++ Algorithms present in the C++/Algorithm folder

### ISSUE THREAD

**Issue by risingstar-bit** [risingstar-bit/Compose-Community#88]
In the DSA/C++/Algorithms folder you need to add README file for Quick sort, Merge sort, Selection sort and Binary search tree to describe its algorithm in details. Don't add source code because it is already there

**Comment by Aishubalaji** [comment]
Can you assign this issue to me?

**Comment by risingstar-bit** [comment]
> Can you assign this issue to me?

Assigned

**Comment by rishabhverma1106** [comment]
Can you assign it to me?
