### ISSUE TITLE
Add Linear search and Binary search algorithm in C++/Algorithm folder

### ISSUE THREAD

**Issue by risingstar-bit** [risingstar-bit/Compose-Community#89]
Add README file for each algorithm in their respective folder. Example C++/Algorithm/BinarySearch folder contains - binary_search (source file) and README.md file

**Comment by vsiddharth365** [comment]
Please assign this to me.

**Comment by risingstar-bit** [comment]
> Please assign this to me @risingstar-bit

assigned

**Comment by Arcturus22** [comment]
Is this issue still open?
I would like to resolve this issue.

**Comment by vsiddharth365** [comment]
> Is this issue still open? I would like to resolve this issue.

The issue is already resolved @risingstar-bit
