### ISSUE TITLE
Add 3 DSA solutions in cpp folder

### ISSUE THREAD

**Issue by risingstar-bit** [risingstar-bit/Compose-Community#90]
you need to write questions description and it's code in one file. example DSA/cpp/ filename.cpp

**Comment by Mr-Sahil-Alam** [comment]
please assign this one to me

**Comment by risingstar-bit** [comment]
> please assign this one to me

Assigned

**Comment by Kritika30032002** [comment]
Assign this to me!

**Comment by risingstar-bit** [comment]
> Assign this to me!

Please Do it. Make sure that your code should be in proper folder

**Comment by Kritika30032002** [comment]
sure!!

**Comment by Kritika30032002** [comment]
You need DSA algo or Just any DSA solutions of leetcode or other platform?

**Comment by risingstar-bit** [comment]
> You need DSA algo or Just any DSA solutions of Leetcode or other platform? @risingstar-bit
> 
> Briefly specify what you actually wanted to be added in this?

Add any DSA problem and its solution of LeetCode.  You need not to add a separate file for the problem statement write in its source code file . 

If the problem statement topic is Array then add your file in DSA/C++/Array_LeetCode. If not available then you have to create folder in C++ .

**Comment by risingstar-bit** [comment]
> > You need DSA algo or Just any DSA solutions of Leetcode or other platform? @risingstar-bit
> > Briefly specify what you actually wanted to be added in this?
> 
> Add any DSA problem and its solution of LeetCode. You need not to add a separate file for the problem statement write in its source code file .
> 
> If the problem statement topic is Array then add your file in DSA/C++/Array_LeetCode. If not available then you have to create folder in C++ .

I made some changes to the repo fork it again if you previously done that

**Comment by Kritika30032002** [comment]
Okay

**Comment by Kritika30032002** [comment]
> > > You need DSA algo or Just any DSA solutions of Leetcode or other platform? @risingstar-bit
> > > Briefly specify what you actually wanted to be added in this?
> > 
> > 
> > Add any DSA problem and its solution of LeetCode. You need not to add a separate file for the problem statement write in its source code file .
> > If the problem statement topic is Array then add your file in DSA/C++/Array_LeetCode. If not available then you have to create folder in C++ .
> 
> I made some changes to the repo fork it again if you previously done that

Done!! 
under PR #126
