### ISSUE TITLE
Add README file for the algorithms present in the DSA/JAVA/Algorithms folder

### ISSUE THREAD

**Issue by risingstar-bit** [risingstar-bit/Compose-Community#91]
In the DSA/JAVA/Algorithms folder you need to add README file for Quick sort, Bubble sort, Selection sort  to describe its algorithm in details. Don't add source code because it is already there

**Comment by Saurabhlucifer** [comment]
Hello! Can you assign me this issue

**Comment by risingstar-bit** [comment]
> Hello! I would like to work . Can you assign me this issue

okay do it except for Bubble Sort Algorithm because some is on that

**Comment by Saurabhlucifer** [comment]
Okay I will complete it as soon as possible.

**Comment by zihadbappy** [comment]
Hi there, I'd like to contribute to this project. Let me know if you need extra help
