### ISSUE TITLE
Javascript notes and Questions 

### ISSUE THREAD

**Issue by Swap-nil-2003** [risingstar-bit/Compose-Community#96]
I would like to contribute a couple of resources on Javascript which would be helpful for those starting off with the language as well as preparing for any interview.

**Comment by Swap-nil-2003** [comment]
@risingstar-bit please assign me this issue if you find it viable.

**Comment by risingstar-bit** [comment]
> I would like to contribute a couple of resources on Javascript which would be helpful for those starting off with the language as well as preparing for any interview.

yes please do it
